### ISSUE TITLE
What license is this toolbox under?

### ISSUE THREAD

**Issue by kimchi-jjigae** [manuels/unix-toolbox.js#4]
Hello, I apologise if creating an issue to ask this question was the wrong way to go about things, but I could not find an e-mail address to send my question to.
Firstly, thanks for a great toolbox.
I'm just wondering what everything is licensed under, if licensed at all, since I wish to use it in another project.

Thanks,
Kim

**Comment by manuels** [comment]
the license of the corresponding software project applies for its js implementation
